spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:5432/payment_system
  jpa:
    hibernate:
      ddl-auto: update
